<?
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["lkg"]["2"]="D";
$PERM["search"]["7"]="W";
$PERM["photo"]["7"]="W";
$PERM["people"]["7"]="W";
$PERM["groups"]["7"]="W";
$PERM["forum"]["7"]="W";
$PERM["blogs"]["7"]="W";
$PERM["index.php"]["7"]="W";
$PERM["pub"]["5"]="T_8";
$PERM["upload"]["5"]="T_8";
$PERM["/"]["*"]="R";
?>