<?require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetTitle("Добавить инициативу");?><?$APPLICATION->IncludeComponent(
	"bitrix:iblock.element.add.form", 
	"initiative", 
	array(
		"CUSTOM_TITLE_DATE_ACTIVE_FROM" => "",
		"CUSTOM_TITLE_DATE_ACTIVE_TO" => "",
		"CUSTOM_TITLE_DETAIL_PICTURE" => "Изображение (формат JPG, PNG, не менее 1000x500 пикселей)",
		"CUSTOM_TITLE_DETAIL_TEXT" => "Решение",
		"CUSTOM_TITLE_IBLOCK_SECTION" => "",
		"CUSTOM_TITLE_NAME" => "Название",
		"CUSTOM_TITLE_PREVIEW_PICTURE" => "",
		"CUSTOM_TITLE_PREVIEW_TEXT" => "Проблема",
		"CUSTOM_TITLE_TAGS" => "",
		"DEFAULT_INPUT_SIZE" => "100",
		"DETAIL_TEXT_USE_HTML_EDITOR" => "Y",
		"ELEMENT_ASSOC" => "CREATED_BY",
		"GROUPS" => array(
			0 => "1",
			1 => "8",
		),
		"IBLOCK_ID" => "13",
		"IBLOCK_TYPE" => "ogas",
		"LEVEL_LAST" => "Y",
		"LIST_URL" => "/lkg/gos/",
		"MAX_FILE_SIZE" => "10000000",
		"MAX_LEVELS" => "100000",
		"MAX_USER_ENTRIES" => "100000",
		"PREVIEW_TEXT_USE_HTML_EDITOR" => "Y",
		"PROPERTY_CODES" => array(
			0 => "54",
			1 => "56",
			2 => "58",
			3 => "59",
			4 => "60",
			5 => "NAME",
			6 => "IBLOCK_SECTION",
			7 => "PREVIEW_TEXT",
			8 => "DETAIL_TEXT",
			9 => "DETAIL_PICTURE",
		),
		"PROPERTY_CODES_REQUIRED" => array(
			0 => "54",
			1 => "59",
			2 => "NAME",
			3 => "PREVIEW_TEXT",
			4 => "DETAIL_TEXT",
			5 => "DETAIL_PICTURE",
		),
		"RESIZE_IMAGES" => "Y",
		"SEF_FOLDER" => "/lkg/gos2/add/",
		"SEF_MODE" => "Y",
		"STATUS" => "ANY",
		"STATUS_NEW" => "N",
		"USER_MESSAGE_ADD" => "",
		"USER_MESSAGE_EDIT" => "",
		"USE_CAPTCHA" => "N",
		"COMPONENT_TEMPLATE" => "initiative"
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>