<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Мои группы");
?><?$APPLICATION->IncludeComponent(
    "bitrix:socialnetwork_group",
    "template1",
    array(
        "ALLOW_POST_MOVE" => "Y",
        "BLOG_ALLOW_POST_CODE" => "Y",
        "BLOG_COMMENT_AJAX_POST" => "N",
        "BLOG_COMMENT_ALLOW_IMAGE_UPLOAD" => "A",
        "BLOG_COMMENT_ALLOW_VIDEO" => "Y",
        "BLOG_GROUP_ID" => "1",
        "BLOG_IMAGE_MAX_HEIGHT" => "600",
        "BLOG_IMAGE_MAX_WIDTH" => "600",
        "BLOG_NO_URL_IN_COMMENTS" => "",
        "BLOG_NO_URL_IN_COMMENTS_AUTHORITY" => "",
        "BLOG_SHOW_SPAM" => "N",
        "BLOG_USE_CUT" => "N",
        "BLOG_USE_GOOGLE_CODE" => "Y",
        "CACHE_TIME" => "3600",
        "CACHE_TIME_LONG" => "604800",
        "CACHE_TYPE" => "A",
        "CAN_OWNER_EDIT_DESKTOP" => "Y",
        "COMPONENT_TEMPLATE" => ".default",
        "DATE_TIME_FORMAT" => "d.m.Y H:i:s",
        "FORUM_AJAX_POST" => "N",
        "FORUM_ID" => "1",
        "FORUM_THEME" => "blue",
        "GROUP_PROPERTY" => array(
        ),
        "GROUP_THUMBNAIL_SIZE" => "",
        "GROUP_USE_BAN" => "N",
        "GROUP_USE_KEYWORDS" => "N",
        "ITEM_DETAIL_COUNT" => "100",
        "ITEM_MAIN_COUNT" => "6",
        "LOG_COMMENT_THUMBNAIL_SIZE" => "",
        "LOG_NEW_TEMPLATE" => "N",
        "LOG_PHOTO_COUNT" => "6",
        "LOG_PHOTO_THUMBNAIL_SIZE" => "48",
        "LOG_RSS_TTL" => "60",
        "LOG_SUBSCRIBE_ONLY" => "N",
        "LOG_THUMBNAIL_SIZE" => "",
        "MAIN_MENU_TYPE" => "top",
        "NAME_TEMPLATE" => "",
        "PATH_TO_BIZPROC_TASK" => "/company/personal/user/#user_id#/bizproc/#id#/",
        "PATH_TO_BIZPROC_TASK_LIST" => "/company/personal/user/#user_id#/bizproc/",
        "PATH_TO_BLOG_SMILE" => "/bitrix/images/blog/smile/",
        "PATH_TO_GROUP_CREATE" => "",
        "PATH_TO_MESSAGES_CHAT" => "/company/personal/messages/chat/#user_id#/",
        "PATH_TO_MESSAGE_FORM_MESS" => "/company/personal/messages/form/#user_id#/#message_id#/",
        "PATH_TO_SEARCH_EXTERNAL" => "",
        "PATH_TO_SMILE" => "/bitrix/images/socialnetwork/smile/",
        "PATH_TO_SUBSCRIBE" => "",
        "PATH_TO_USER" => "/user/#user_id#/",
        "PATH_TO_USER_BLOG_POST" => "",
        "PATH_TO_USER_BLOG_POST_EDIT" => "",
        "PATH_TO_USER_BLOG_POST_IMPORTANT" => "user/#user_id#/blog/important/",
        "PATH_TO_USER_CALENDAR" => "/company/personal/user/#user_id#/calendar/",
        "PATH_TO_USER_LOG" => "/company/personal/log/",
        "PATH_TO_USER_LOG_ENTRY" => "/company/personal/log/#log_id#/",
        "PATH_TO_USER_TASKS_TEMPLATES" => "/company/personal/user/#user_id#/tasks/templates/",
        "PATH_TO_USER_TEMPLATES_TEMPLATE" => "/company/personal/user/#user_id#/tasks/templates/template/#action#/#template_id#/",
        "PHOTO_ALBUM_PHOTO_THUMBS_SIZE" => "120",
        "PHOTO_ELEMENTS_PAGE_ELEMENTS" => "50",
        "PHOTO_GROUP_IBLOCK_ID" => "1",
        "PHOTO_GROUP_IBLOCK_TYPE" => "photos",
        "PHOTO_MODERATION" => "N",
        "PHOTO_ORIGINAL_SIZE" => "1280",
        "PHOTO_PATH_TO_FONT" => "",
        "PHOTO_SECTION_PAGE_ELEMENTS" => "15",
        "PHOTO_SHOW_WATERMARK" => "Y",
        "PHOTO_THUMBNAIL_SIZE" => "100",
        "PHOTO_UPLOAD_MAX_FILESIZE" => "1047527424",
        "PHOTO_USE_COMMENTS" => "N",
        "PHOTO_USE_RATING" => "N",
        "PHOTO_WATERMARK_MIN_PICTURE_SIZE" => "400",
        "PHOTO_WATERMARK_RULES" => "USER",
        "RATING_ID" => array(
        ),
        "RATING_TYPE" => "",
        "SEARCH_DEFAULT_SORT" => "rank",
        "SEARCH_FILTER_DATE_NAME" => "sonet_search_filter_date",
        "SEARCH_FILTER_NAME" => "sonet_search_filter",
        "SEARCH_PAGE_RESULT_COUNT" => "10",
        "SEARCH_RESTART" => "N",
        "SEARCH_TAGS_COLOR_NEW" => "3E74E6",
        "SEARCH_TAGS_COLOR_OLD" => "C0C0C0",
        "SEARCH_TAGS_FONT_MAX" => "50",
        "SEARCH_TAGS_FONT_MIN" => "10",
        "SEARCH_TAGS_PAGE_ELEMENTS" => "100",
        "SEARCH_TAGS_PERIOD" => "",
        "SEARCH_USE_LANGUAGE_GUESS" => "Y",
        "SEF_FOLDER" => "/groups/",
        "SEF_MODE" => "Y",
        "SET_NAV_CHAIN" => "N",
        "SET_TITLE" => "N",
        "SHOW_LOGIN" => "Y",
        "SHOW_RATING" => "",
        "SHOW_SEARCH_TAGS_CLOUD" => "Y",
        "SHOW_VOTE" => "N",
        "SHOW_YEAR" => "Y",
        "SM_THEME" => "grey",
        "USER_FIELDS_FORUM" => array(
        ),
        "USER_PROPERTY_CONTACT" => array(
        ),
        "USER_PROPERTY_MAIN" => array(
        ),
        "USER_PROPERTY_PERSONAL" => array(
        ),
        "USE_MAIN_MENU" => "N",
        "PATH_TO_BLOG_POST" => "",
        "PATH_TO_BLOG_POST_EDIT" => "",
        "PATH_TO_BLOG_DRAFT" => "",
        "PATH_TO_BLOG_BLOG" => "",
        "PATH_TO_USER_POST" => "",
        "PATH_TO_USER_POST_EDIT" => "",
        "PATH_TO_USER_DRAFT" => "",
        "PATH_TO_USER_BLOG" => "",
        "SEF_URL_TEMPLATES" => array(
            "index" => "index.php",
            "search" => "search.php",
            "group_reindex" => "group_reindex.php",
            "group_content_search" => "group/#group_id#/search/",
            "group_subscribe" => "group/#group_id#/subscribe/",
            "group" => "group/#group_id#/",
            "group_search" => "group/search/",
            "group_search_subject" => "group/search/#subject_id#/",
            "group_edit" => "group/#group_id#/edit/",
            "group_delete" => "group/#group_id#/delete/",
            "group_request_search" => "group/#group_id#/user_search/",
            "group_request_user" => "group/#group_id#/user/#user_id#/request/",
            "user_request_group" => "group/#group_id#/user_request/",
            "group_requests" => "group/#group_id#/requests/",
            "group_requests_out" => "group/#group_id#/requests_out/",
            "group_mods" => "group/#group_id#/moderators/",
            "group_users" => "group/#group_id#/users/",
            "group_ban" => "group/#group_id#/ban/",
            "user_leave_group" => "group/#group_id#/user_leave/",
            "group_features" => "group/#group_id#/features/",
            "group_log" => "group/#group_id#/log/",
            "group_photo" => "group/#group_id#/photo/",
            "group_calendar" => "group/#group_id#/calendar/",
            "group_files" => "group/#group_id#/files/#path#",
            "group_blog" => "group/#group_id#/blog/",
            "group_blog_post_edit" => "group/#group_id#/blog/edit/#post_id#/",
            "group_blog_rss" => "group/#group_id#/blog/rss/#type#/",
            "group_blog_draft" => "group/#group_id#/blog/draft/",
            "group_blog_post" => "group/#group_id#/blog/#post_id#/",
            "group_blog_moderation" => "group/#group_id#/blog/moderation/",
            "group_forum" => "group/#group_id#/forum/",
            "group_forum_topic_edit" => "group/#group_id#/forum/edit/#topic_id#/",
            "group_forum_topic" => "group/#group_id#/forum/#topic_id#/",
        )
    ),
    false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>